### ISSUE TITLE
Assertion triggered when decoding some bad image

### ISSUE THREAD

**Issue by FranciscoDS** [dmtx/libdmtx#5]
Tested with last source code, when trying to dmtxread the attached image, libdtmx tries to decode a datamatrix which doesn't exist, find an invalid sequence and an assert is triggered :

```
#0  0x00007ffff6b4e1d7 in raise () from /lib64/libc.so.6
#1  0x00007ffff6b4f8c8 in abort () from /lib64/libc.so.6
#2  0x00007ffff6b47146 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff6b471f2 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000409e90 in PushOutputWord (msg=0x6372e0, value=-1)
    at dmtxdecodescheme.c:128
#5  0x000000000040a1b5 in DecodeSchemeAscii (msg=0x6372e0, 
    ptr=0x6371f2 "\372$\255\071;\340", dataEnd=0x6371f3 "$\255\071;\340")
    at dmtxdecodescheme.c:226
#6  0x0000000000409d5f in DecodeDataStream (msg=0x6372e0, sizeIdx=0, 
    outputStart=0x0) at dmtxdecodescheme.c:60
#7  0x0000000000408f91 in dmtxDecodePopulatedArray (sizeIdx=0, msg=0x6372e0, 
    fix=-1) at dmtxdecode.c:402
#8  0x0000000000408f10 in dmtxDecodeMatrixRegion (dec=0x634af0, reg=0x63afd0, 
    fix=-1) at dmtxdecode.c:359
#9  0x0000000000401ad9 in main (argc=3, argv=0x7fffffffdde8) at dmtxread.c:162
```

In DecodeSchemeAscii at dmtxdecodescheme.c:226 a codeword=0 is found which can't happen in a valid datamatrix :
```
225	      else if(codeword <= 128) {
226	         PushOutputWord(msg, codeword - 1);
227	      }
```

In PushOutputWord at dmtxdecodescheme.c:128 assertion fails due to the invalid value=-1
```
125	static void
126	PushOutputWord(DmtxMessage *msg, int value)
127	{
128	   assert(value >= 0 && value < 256);
129	
130	   msg->output[msg->outputIdx++] = (unsigned char)value;
131	}
```

The following minimal image triggers this fatal abort (tested with dmtxread -n test1.png).

![test1](https://user-images.githubusercontent.com/3823823/29824217-2c29bdc8-8cd1-11e7-8ef6-3f015af59788.png)

**Comment by ninafiona** [comment]
Why is this issue closed? I came across the same issue just now.
